---
title: "Summary of new results on initial lengthening"
author: "Frederic Blum"
date: "2022-12-24"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE,
                      fig.align = 'center')
```

# Summary of new results

## Introduction

This short documents presents the most recent update to the study on initial lengthening (and shortening) of consonants.
It includes the full DoReCo data set of 51 languages and shows promising result.
Ludger presented a first talk on this during the ALT conference.

## Results

```{r data, include=FALSE}
library(bayesplot)
library(brms)
library(tidyverse)
library(tidybayes)
library(patchwork)
library(viridis)
library(xtable)
source("cl_helper_functions.R")

###################################################################
cl_max_sep <- readRDS(file="../models/cl_max_small.rds")

rope_high=0.01
rope_low=-0.01

#########################################
###     Parameters                    ###
#########################################
hpdi_vals89 <- posterior_interval(cl_max_sep, prob=0.89) %>% 
  data.frame() %>% as_tibble(rownames="Parameter") %>% 
  rename(hpdi_89_low=X5.5., hpdi_89_high=X94.5.)

hpdi_vals99 <- posterior_interval(cl_max_sep, prob=0.997) %>% 
  data.frame() %>% as_tibble(rownames="Parameter") %>% 
  rename(hpdi_low=X0.15., hpdi_high=X99.85.)

para_vals <- posterior_summary(cl_max_sep) %>% 
  data.frame() %>% as_tibble(rownames="Parameter") %>% 
  left_join(hpdi_vals89) %>% left_join(hpdi_vals99) %>% 
  mutate(Parameter=str_replace(Parameter, "utt", "utterance-initial"),
         Parameter=str_replace(Parameter, "word", "word-initial"))%>%
  mutate(Parameter=str_replace(Parameter, "_initial1", "")) 

rm(hpdi_vals89, hpdi_vals99)

fix_eff <- para_vals %>% 
  filter(Parameter == "b_word-initial"|Parameter == "b_utterance-initial") %>% 
  mutate(Parameter=str_replace(Parameter, "b_", ""))

lang_params <- para_vals %>% 
  filter(grepl("^r_Language\\[.*", Parameter)) %>% 
  mutate(Parameter=gsub("r_Language\\[(.*)(,-initial|,)(.*)]", "\\1__\\3", Parameter)) %>% 
  separate(sep="__", col=Parameter, into=c("Language", "Parameter")) %>% 
  filter(Parameter != "Intercept") %>% 
  left_join(fix_eff, by="Parameter") %>% 
  transmute(
    Language=Language, Parameter=Parameter,
    Estimate=Estimate.x + Estimate.y,
     hpdi_89_high=hpdi_89_high.x + hpdi_89_high.y,
     hpdi_89_low=hpdi_89_low.x + hpdi_89_low.y,
     hpdi_high=hpdi_high.x + hpdi_high.y,
     hpdi_low=hpdi_low.x + hpdi_low.y
   ) %>% 
  mutate(outside=ifelse(hpdi_89_high < rope_low, TRUE, 
                          ifelse(hpdi_89_low > rope_high, TRUE, FALSE)),
         outside_99=ifelse(hpdi_high < rope_low, "yes", 
                             ifelse(hpdi_low > rope_high, "yes", "no")),
         Language=str_replace(Language, "\\.", " "))

langWord <- lang_params %>% filter(Parameter == "word-initial")
langUtt <- lang_params %>% filter(Parameter == "utterance-initial")

languages <- read_csv('./utils/languages.csv')

pop_level <- c("b_Initialutterance-initial", "b_Initialword-initial", 
                "b_z_logSpeechRate" , "b_z_logPhonWord",
                "b_z_logWordFormFreq", "b_ConCluster")

#########################################
###     Language plots                ###
#########################################
word_init <- langWord %>% 
  ggplot(aes(x=Estimate, y=reorder(Language, Estimate))) +
  geom_linerange(aes(xmin=hpdi_low, xmax=hpdi_high)) + 
  geom_pointrange(aes(xmin=hpdi_89_low, xmax=hpdi_89_high, color=Parameter,
                      alpha=ifelse(outside == 1, 1, 0.5)), size=1) +  
  geom_vline(xintercept=0, color="red") +
  annotate("rect", xmin=rope_low, xmax=rope_high, ymin=0, ymax=Inf, alpha=.2) +
  scale_y_discrete(name=NULL) +
  scale_color_viridis(discrete=T, end=0.7) +
  scale_x_continuous(name=NULL) +
  theme(legend.position="none")

word_init
###################################################################
utt_init <- langUtt %>% 
  ggplot(aes(x=Estimate, y=reorder(Language, Estimate))) +
  geom_linerange(aes(xmin=hpdi_low, xmax=hpdi_high)) + 
  geom_pointrange(aes(xmin=hpdi_89_low, xmax=hpdi_89_high, color=Parameter,
                      alpha=ifelse(outside == 1, 1, 0.5)), size=1) +  
  geom_vline(xintercept=0, color="red") +
  annotate("rect", xmin=rope_low, xmax=rope_high, ymin=0, ymax=Inf, alpha=.2) +
  scale_y_discrete(name=NULL) +
  scale_color_viridis(discrete=T, end=0.7) +
  scale_x_continuous(name=NULL) +
  theme(legend.position="none")

utt_init
```

```{r plots}
word_init
utt_init
```
```